// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package datumclient

import (
	"context"
	"net/http"
	"time"

	"github.com/Yamashou/gqlgenc/clientv2"
	"github.com/datumforge/datum/internal/ent/generated"
	"github.com/datumforge/datum/internal/ent/generated/usersetting"
)

type DatumClient interface {
	GetOrganizationByID(ctx context.Context, organizationID string, interceptors ...clientv2.RequestInterceptor) (*GetOrganizationByID, error)
	GetAllOrganizations(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetAllOrganizations, error)
	CreateOrganization(ctx context.Context, input CreateOrganizationInput, interceptors ...clientv2.RequestInterceptor) (*CreateOrganization, error)
	UpdateOrganization(ctx context.Context, updateOrganizationID string, input UpdateOrganizationInput, interceptors ...clientv2.RequestInterceptor) (*UpdateOrganization, error)
	DeleteOrganization(ctx context.Context, deleteOrganizationID string, interceptors ...clientv2.RequestInterceptor) (*DeleteOrganization, error)
	GetUserByID(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUserByID, error)
	GetUserByIDWithOrgs(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUserByIDWithOrgs, error)
	GetAllUsers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetAllUsers, error)
	CreateUser(ctx context.Context, input CreateUserInput, interceptors ...clientv2.RequestInterceptor) (*CreateUser, error)
	UpdateUser(ctx context.Context, updateUserID string, input UpdateUserInput, interceptors ...clientv2.RequestInterceptor) (*UpdateUser, error)
	DeleteUser(ctx context.Context, deleteUserID string, interceptors ...clientv2.RequestInterceptor) (*DeleteUser, error)
}

type Client struct {
	Client *clientv2.Client
}

func NewClient(cli *http.Client, baseURL string, options *clientv2.Options, interceptors ...clientv2.RequestInterceptor) DatumClient {
	return &Client{Client: clientv2.NewClient(cli, baseURL, options, interceptors...)}
}

type Query struct {
	Node                 generated.Noder               "json:\"node,omitempty\" graphql:\"node\""
	Nodes                []generated.Noder             "json:\"nodes\" graphql:\"nodes\""
	Entitlements         EntitlementConnection         "json:\"entitlements\" graphql:\"entitlements\""
	Groups               GroupConnection               "json:\"groups\" graphql:\"groups\""
	GroupSettings        GroupSettingConnection        "json:\"groupSettings\" graphql:\"groupSettings\""
	Integrations         IntegrationConnection         "json:\"integrations\" graphql:\"integrations\""
	OauthProviders       OauthProviderConnection       "json:\"oauthProviders\" graphql:\"oauthProviders\""
	Organizations        OrganizationConnection        "json:\"organizations\" graphql:\"organizations\""
	OrganizationSettings OrganizationSettingConnection "json:\"organizationSettings\" graphql:\"organizationSettings\""
	PersonalAccessTokens PersonalAccessTokenConnection "json:\"personalAccessTokens\" graphql:\"personalAccessTokens\""
	RefreshTokens        RefreshTokenConnection        "json:\"refreshTokens\" graphql:\"refreshTokens\""
	Sessions             SessionConnection             "json:\"sessions\" graphql:\"sessions\""
	Users                UserConnection                "json:\"users\" graphql:\"users\""
	UserSettings         UserSettingConnection         "json:\"userSettings\" graphql:\"userSettings\""
	Entitlement          Entitlement                   "json:\"entitlement\" graphql:\"entitlement\""
	Group                Group                         "json:\"group\" graphql:\"group\""
	GroupSetting         GroupSetting                  "json:\"groupSetting\" graphql:\"groupSetting\""
	Integration          Integration                   "json:\"integration\" graphql:\"integration\""
	OauthProvider        OauthProvider                 "json:\"oauthProvider\" graphql:\"oauthProvider\""
	Organization         Organization                  "json:\"organization\" graphql:\"organization\""
	OrganizationSetting  OrganizationSetting           "json:\"organizationSetting\" graphql:\"organizationSetting\""
	PersonalAccessToken  PersonalAccessToken           "json:\"personalAccessToken\" graphql:\"personalAccessToken\""
	RefreshToken         RefreshToken                  "json:\"refreshToken\" graphql:\"refreshToken\""
	Session              Session                       "json:\"session\" graphql:\"session\""
	User                 User                          "json:\"user\" graphql:\"user\""
	UserSetting          UserSetting                   "json:\"userSetting\" graphql:\"userSetting\""
	Service              Service                       "json:\"_service\" graphql:\"_service\""
}
type Mutation struct {
	CreateEntitlement         EntitlementCreatePayload         "json:\"createEntitlement\" graphql:\"createEntitlement\""
	UpdateEntitlement         EntitlementUpdatePayload         "json:\"updateEntitlement\" graphql:\"updateEntitlement\""
	DeleteEntitlement         EntitlementDeletePayload         "json:\"deleteEntitlement\" graphql:\"deleteEntitlement\""
	CreateGroup               GroupCreatePayload               "json:\"createGroup\" graphql:\"createGroup\""
	UpdateGroup               GroupUpdatePayload               "json:\"updateGroup\" graphql:\"updateGroup\""
	DeleteGroup               GroupDeletePayload               "json:\"deleteGroup\" graphql:\"deleteGroup\""
	CreateGroupSetting        GroupSettingCreatePayload        "json:\"createGroupSetting\" graphql:\"createGroupSetting\""
	UpdateGroupSetting        GroupSettingUpdatePayload        "json:\"updateGroupSetting\" graphql:\"updateGroupSetting\""
	DeleteGroupSetting        GroupSettingDeletePayload        "json:\"deleteGroupSetting\" graphql:\"deleteGroupSetting\""
	CreateIntegration         IntegrationCreatePayload         "json:\"createIntegration\" graphql:\"createIntegration\""
	UpdateIntegration         IntegrationUpdatePayload         "json:\"updateIntegration\" graphql:\"updateIntegration\""
	DeleteIntegration         IntegrationDeletePayload         "json:\"deleteIntegration\" graphql:\"deleteIntegration\""
	CreateOauthProvider       OauthProviderCreatePayload       "json:\"createOauthProvider\" graphql:\"createOauthProvider\""
	UpdateOauthProvider       OauthProviderUpdatePayload       "json:\"updateOauthProvider\" graphql:\"updateOauthProvider\""
	DeleteOauthProvider       OauthProviderDeletePayload       "json:\"deleteOauthProvider\" graphql:\"deleteOauthProvider\""
	CreateOrganization        OrganizationCreatePayload        "json:\"createOrganization\" graphql:\"createOrganization\""
	UpdateOrganization        OrganizationUpdatePayload        "json:\"updateOrganization\" graphql:\"updateOrganization\""
	DeleteOrganization        OrganizationDeletePayload        "json:\"deleteOrganization\" graphql:\"deleteOrganization\""
	CreateOrganizationSetting OrganizationSettingCreatePayload "json:\"createOrganizationSetting\" graphql:\"createOrganizationSetting\""
	UpdateOrganizationSetting OrganizationSettingUpdatePayload "json:\"updateOrganizationSetting\" graphql:\"updateOrganizationSetting\""
	DeleteOrganizationSetting OrganizationSettingDeletePayload "json:\"deleteOrganizationSetting\" graphql:\"deleteOrganizationSetting\""
	CreatePersonalAccessToken PersonalAccessTokenCreatePayload "json:\"createPersonalAccessToken\" graphql:\"createPersonalAccessToken\""
	UpdatePersonalAccessToken PersonalAccessTokenUpdatePayload "json:\"updatePersonalAccessToken\" graphql:\"updatePersonalAccessToken\""
	DeletePersonalAccessToken PersonalAccessTokenDeletePayload "json:\"deletePersonalAccessToken\" graphql:\"deletePersonalAccessToken\""
	CreateRefreshToken        RefreshTokenCreatePayload        "json:\"createRefreshToken\" graphql:\"createRefreshToken\""
	UpdateRefreshToken        RefreshTokenUpdatePayload        "json:\"updateRefreshToken\" graphql:\"updateRefreshToken\""
	DeleteRefreshToken        RefreshTokenDeletePayload        "json:\"deleteRefreshToken\" graphql:\"deleteRefreshToken\""
	CreateSession             SessionCreatePayload             "json:\"createSession\" graphql:\"createSession\""
	UpdateSession             SessionUpdatePayload             "json:\"updateSession\" graphql:\"updateSession\""
	DeleteSession             SessionDeletePayload             "json:\"deleteSession\" graphql:\"deleteSession\""
	CreateUser                UserCreatePayload                "json:\"createUser\" graphql:\"createUser\""
	UpdateUser                UserUpdatePayload                "json:\"updateUser\" graphql:\"updateUser\""
	DeleteUser                UserDeletePayload                "json:\"deleteUser\" graphql:\"deleteUser\""
	CreateUserSetting         UserSettingCreatePayload         "json:\"createUserSetting\" graphql:\"createUserSetting\""
	UpdateUserSetting         UserSettingUpdatePayload         "json:\"updateUserSetting\" graphql:\"updateUserSetting\""
	DeleteUserSetting         UserSettingDeletePayload         "json:\"deleteUserSetting\" graphql:\"deleteUserSetting\""
}
type GetOrganizationByID_Organization struct {
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy   *string   "json:\"createdBy,omitempty\" graphql:\"createdBy\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	UpdatedBy   *string   "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
}

func (t *GetOrganizationByID_Organization) GetID() string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.ID
}
func (t *GetOrganizationByID_Organization) GetName() string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.Name
}
func (t *GetOrganizationByID_Organization) GetDisplayName() string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.DisplayName
}
func (t *GetOrganizationByID_Organization) GetDescription() *string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.Description
}
func (t *GetOrganizationByID_Organization) GetCreatedAt() *time.Time {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return &t.CreatedAt
}
func (t *GetOrganizationByID_Organization) GetCreatedBy() *string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.CreatedBy
}
func (t *GetOrganizationByID_Organization) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return &t.UpdatedAt
}
func (t *GetOrganizationByID_Organization) GetUpdatedBy() *string {
	if t == nil {
		t = &GetOrganizationByID_Organization{}
	}
	return t.UpdatedBy
}

type GetAllOrganizations_Organizations_Edges_Node struct {
	ID          string  "json:\"id\" graphql:\"id\""
	Name        string  "json:\"name\" graphql:\"name\""
	DisplayName string  "json:\"displayName\" graphql:\"displayName\""
	Description *string "json:\"description,omitempty\" graphql:\"description\""
}

func (t *GetAllOrganizations_Organizations_Edges_Node) GetID() string {
	if t == nil {
		t = &GetAllOrganizations_Organizations_Edges_Node{}
	}
	return t.ID
}
func (t *GetAllOrganizations_Organizations_Edges_Node) GetName() string {
	if t == nil {
		t = &GetAllOrganizations_Organizations_Edges_Node{}
	}
	return t.Name
}
func (t *GetAllOrganizations_Organizations_Edges_Node) GetDisplayName() string {
	if t == nil {
		t = &GetAllOrganizations_Organizations_Edges_Node{}
	}
	return t.DisplayName
}
func (t *GetAllOrganizations_Organizations_Edges_Node) GetDescription() *string {
	if t == nil {
		t = &GetAllOrganizations_Organizations_Edges_Node{}
	}
	return t.Description
}

type GetAllOrganizations_Organizations_Edges struct {
	Node *GetAllOrganizations_Organizations_Edges_Node "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetAllOrganizations_Organizations_Edges) GetNode() *GetAllOrganizations_Organizations_Edges_Node {
	if t == nil {
		t = &GetAllOrganizations_Organizations_Edges{}
	}
	return t.Node
}

type GetAllOrganizations_Organizations struct {
	Edges []*GetAllOrganizations_Organizations_Edges "json:\"edges,omitempty\" graphql:\"edges\""
}

func (t *GetAllOrganizations_Organizations) GetEdges() []*GetAllOrganizations_Organizations_Edges {
	if t == nil {
		t = &GetAllOrganizations_Organizations{}
	}
	return t.Edges
}

type CreateOrganization_CreateOrganization_Organization struct {
	ID          string    "json:\"id\" graphql:\"id\""
	Name        string    "json:\"name\" graphql:\"name\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	Description *string   "json:\"description,omitempty\" graphql:\"description\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy   *string   "json:\"createdBy,omitempty\" graphql:\"createdBy\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	UpdatedBy   *string   "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
}

func (t *CreateOrganization_CreateOrganization_Organization) GetID() string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.ID
}
func (t *CreateOrganization_CreateOrganization_Organization) GetName() string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.Name
}
func (t *CreateOrganization_CreateOrganization_Organization) GetDisplayName() string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.DisplayName
}
func (t *CreateOrganization_CreateOrganization_Organization) GetDescription() *string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.Description
}
func (t *CreateOrganization_CreateOrganization_Organization) GetCreatedAt() *time.Time {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return &t.CreatedAt
}
func (t *CreateOrganization_CreateOrganization_Organization) GetCreatedBy() *string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.CreatedBy
}
func (t *CreateOrganization_CreateOrganization_Organization) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return &t.UpdatedAt
}
func (t *CreateOrganization_CreateOrganization_Organization) GetUpdatedBy() *string {
	if t == nil {
		t = &CreateOrganization_CreateOrganization_Organization{}
	}
	return t.UpdatedBy
}

type CreateOrganization_CreateOrganization struct {
	Organization CreateOrganization_CreateOrganization_Organization "json:\"organization\" graphql:\"organization\""
}

func (t *CreateOrganization_CreateOrganization) GetOrganization() *CreateOrganization_CreateOrganization_Organization {
	if t == nil {
		t = &CreateOrganization_CreateOrganization{}
	}
	return &t.Organization
}

type UpdateOrganization_UpdateOrganization_Organization struct {
	ID          string  "json:\"id\" graphql:\"id\""
	Name        string  "json:\"name\" graphql:\"name\""
	DisplayName string  "json:\"displayName\" graphql:\"displayName\""
	Description *string "json:\"description,omitempty\" graphql:\"description\""
}

func (t *UpdateOrganization_UpdateOrganization_Organization) GetID() string {
	if t == nil {
		t = &UpdateOrganization_UpdateOrganization_Organization{}
	}
	return t.ID
}
func (t *UpdateOrganization_UpdateOrganization_Organization) GetName() string {
	if t == nil {
		t = &UpdateOrganization_UpdateOrganization_Organization{}
	}
	return t.Name
}
func (t *UpdateOrganization_UpdateOrganization_Organization) GetDisplayName() string {
	if t == nil {
		t = &UpdateOrganization_UpdateOrganization_Organization{}
	}
	return t.DisplayName
}
func (t *UpdateOrganization_UpdateOrganization_Organization) GetDescription() *string {
	if t == nil {
		t = &UpdateOrganization_UpdateOrganization_Organization{}
	}
	return t.Description
}

type UpdateOrganization_UpdateOrganization struct {
	Organization UpdateOrganization_UpdateOrganization_Organization "json:\"organization\" graphql:\"organization\""
}

func (t *UpdateOrganization_UpdateOrganization) GetOrganization() *UpdateOrganization_UpdateOrganization_Organization {
	if t == nil {
		t = &UpdateOrganization_UpdateOrganization{}
	}
	return &t.Organization
}

type DeleteOrganization_DeleteOrganization struct {
	DeletedID string "json:\"deletedID\" graphql:\"deletedID\""
}

func (t *DeleteOrganization_DeleteOrganization) GetDeletedID() string {
	if t == nil {
		t = &DeleteOrganization_DeleteOrganization{}
	}
	return t.DeletedID
}

type GetUserByID_User_Setting struct {
	Status         usersetting.Status "json:\"status\" graphql:\"status\""
	Locked         bool               "json:\"locked\" graphql:\"locked\""
	EmailConfirmed bool               "json:\"emailConfirmed\" graphql:\"emailConfirmed\""
}

func (t *GetUserByID_User_Setting) GetStatus() *usersetting.Status {
	if t == nil {
		t = &GetUserByID_User_Setting{}
	}
	return &t.Status
}
func (t *GetUserByID_User_Setting) GetLocked() bool {
	if t == nil {
		t = &GetUserByID_User_Setting{}
	}
	return t.Locked
}
func (t *GetUserByID_User_Setting) GetEmailConfirmed() bool {
	if t == nil {
		t = &GetUserByID_User_Setting{}
	}
	return t.EmailConfirmed
}

type GetUserByID_User struct {
	ID          string                   "json:\"id\" graphql:\"id\""
	FirstName   string                   "json:\"firstName\" graphql:\"firstName\""
	LastName    string                   "json:\"lastName\" graphql:\"lastName\""
	Email       string                   "json:\"email\" graphql:\"email\""
	DisplayName string                   "json:\"displayName\" graphql:\"displayName\""
	Setting     GetUserByID_User_Setting "json:\"setting\" graphql:\"setting\""
}

func (t *GetUserByID_User) GetID() string {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return t.ID
}
func (t *GetUserByID_User) GetFirstName() string {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return t.FirstName
}
func (t *GetUserByID_User) GetLastName() string {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return t.LastName
}
func (t *GetUserByID_User) GetEmail() string {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return t.Email
}
func (t *GetUserByID_User) GetDisplayName() string {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return t.DisplayName
}
func (t *GetUserByID_User) GetSetting() *GetUserByID_User_Setting {
	if t == nil {
		t = &GetUserByID_User{}
	}
	return &t.Setting
}

type GetUserByIDWithOrgs_User_Setting struct {
	Status         usersetting.Status "json:\"status\" graphql:\"status\""
	Locked         bool               "json:\"locked\" graphql:\"locked\""
	EmailConfirmed bool               "json:\"emailConfirmed\" graphql:\"emailConfirmed\""
}

func (t *GetUserByIDWithOrgs_User_Setting) GetStatus() *usersetting.Status {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Setting{}
	}
	return &t.Status
}
func (t *GetUserByIDWithOrgs_User_Setting) GetLocked() bool {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Setting{}
	}
	return t.Locked
}
func (t *GetUserByIDWithOrgs_User_Setting) GetEmailConfirmed() bool {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Setting{}
	}
	return t.EmailConfirmed
}

type GetUserByIDWithOrgs_User_Organizations struct {
	ID          string "json:\"id\" graphql:\"id\""
	Name        string "json:\"name\" graphql:\"name\""
	DisplayName string "json:\"displayName\" graphql:\"displayName\""
}

func (t *GetUserByIDWithOrgs_User_Organizations) GetID() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Organizations{}
	}
	return t.ID
}
func (t *GetUserByIDWithOrgs_User_Organizations) GetName() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Organizations{}
	}
	return t.Name
}
func (t *GetUserByIDWithOrgs_User_Organizations) GetDisplayName() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User_Organizations{}
	}
	return t.DisplayName
}

type GetUserByIDWithOrgs_User struct {
	ID            string                                    "json:\"id\" graphql:\"id\""
	FirstName     string                                    "json:\"firstName\" graphql:\"firstName\""
	LastName      string                                    "json:\"lastName\" graphql:\"lastName\""
	Email         string                                    "json:\"email\" graphql:\"email\""
	DisplayName   string                                    "json:\"displayName\" graphql:\"displayName\""
	Setting       GetUserByIDWithOrgs_User_Setting          "json:\"setting\" graphql:\"setting\""
	Organizations []*GetUserByIDWithOrgs_User_Organizations "json:\"organizations,omitempty\" graphql:\"organizations\""
}

func (t *GetUserByIDWithOrgs_User) GetID() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.ID
}
func (t *GetUserByIDWithOrgs_User) GetFirstName() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.FirstName
}
func (t *GetUserByIDWithOrgs_User) GetLastName() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.LastName
}
func (t *GetUserByIDWithOrgs_User) GetEmail() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.Email
}
func (t *GetUserByIDWithOrgs_User) GetDisplayName() string {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.DisplayName
}
func (t *GetUserByIDWithOrgs_User) GetSetting() *GetUserByIDWithOrgs_User_Setting {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return &t.Setting
}
func (t *GetUserByIDWithOrgs_User) GetOrganizations() []*GetUserByIDWithOrgs_User_Organizations {
	if t == nil {
		t = &GetUserByIDWithOrgs_User{}
	}
	return t.Organizations
}

type GetAllUsers_Users_Edges_Node_Setting struct {
	Status         usersetting.Status "json:\"status\" graphql:\"status\""
	Locked         bool               "json:\"locked\" graphql:\"locked\""
	EmailConfirmed bool               "json:\"emailConfirmed\" graphql:\"emailConfirmed\""
}

func (t *GetAllUsers_Users_Edges_Node_Setting) GetStatus() *usersetting.Status {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node_Setting{}
	}
	return &t.Status
}
func (t *GetAllUsers_Users_Edges_Node_Setting) GetLocked() bool {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node_Setting{}
	}
	return t.Locked
}
func (t *GetAllUsers_Users_Edges_Node_Setting) GetEmailConfirmed() bool {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node_Setting{}
	}
	return t.EmailConfirmed
}

type GetAllUsers_Users_Edges_Node struct {
	ID          string                               "json:\"id\" graphql:\"id\""
	FirstName   string                               "json:\"firstName\" graphql:\"firstName\""
	LastName    string                               "json:\"lastName\" graphql:\"lastName\""
	Email       string                               "json:\"email\" graphql:\"email\""
	DisplayName string                               "json:\"displayName\" graphql:\"displayName\""
	Setting     GetAllUsers_Users_Edges_Node_Setting "json:\"setting\" graphql:\"setting\""
}

func (t *GetAllUsers_Users_Edges_Node) GetID() string {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return t.ID
}
func (t *GetAllUsers_Users_Edges_Node) GetFirstName() string {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return t.FirstName
}
func (t *GetAllUsers_Users_Edges_Node) GetLastName() string {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return t.LastName
}
func (t *GetAllUsers_Users_Edges_Node) GetEmail() string {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return t.Email
}
func (t *GetAllUsers_Users_Edges_Node) GetDisplayName() string {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return t.DisplayName
}
func (t *GetAllUsers_Users_Edges_Node) GetSetting() *GetAllUsers_Users_Edges_Node_Setting {
	if t == nil {
		t = &GetAllUsers_Users_Edges_Node{}
	}
	return &t.Setting
}

type GetAllUsers_Users_Edges struct {
	Node *GetAllUsers_Users_Edges_Node "json:\"node,omitempty\" graphql:\"node\""
}

func (t *GetAllUsers_Users_Edges) GetNode() *GetAllUsers_Users_Edges_Node {
	if t == nil {
		t = &GetAllUsers_Users_Edges{}
	}
	return t.Node
}

type GetAllUsers_Users struct {
	Edges []*GetAllUsers_Users_Edges "json:\"edges,omitempty\" graphql:\"edges\""
}

func (t *GetAllUsers_Users) GetEdges() []*GetAllUsers_Users_Edges {
	if t == nil {
		t = &GetAllUsers_Users{}
	}
	return t.Edges
}

type CreateUser_CreateUser_User_Setting struct {
	Status         usersetting.Status "json:\"status\" graphql:\"status\""
	Locked         bool               "json:\"locked\" graphql:\"locked\""
	EmailConfirmed bool               "json:\"emailConfirmed\" graphql:\"emailConfirmed\""
}

func (t *CreateUser_CreateUser_User_Setting) GetStatus() *usersetting.Status {
	if t == nil {
		t = &CreateUser_CreateUser_User_Setting{}
	}
	return &t.Status
}
func (t *CreateUser_CreateUser_User_Setting) GetLocked() bool {
	if t == nil {
		t = &CreateUser_CreateUser_User_Setting{}
	}
	return t.Locked
}
func (t *CreateUser_CreateUser_User_Setting) GetEmailConfirmed() bool {
	if t == nil {
		t = &CreateUser_CreateUser_User_Setting{}
	}
	return t.EmailConfirmed
}

type CreateUser_CreateUser_User struct {
	ID          string                             "json:\"id\" graphql:\"id\""
	FirstName   string                             "json:\"firstName\" graphql:\"firstName\""
	LastName    string                             "json:\"lastName\" graphql:\"lastName\""
	Email       string                             "json:\"email\" graphql:\"email\""
	DisplayName string                             "json:\"displayName\" graphql:\"displayName\""
	Setting     CreateUser_CreateUser_User_Setting "json:\"setting\" graphql:\"setting\""
	CreatedAt   time.Time                          "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy   *string                            "json:\"createdBy,omitempty\" graphql:\"createdBy\""
	UpdatedAt   time.Time                          "json:\"updatedAt\" graphql:\"updatedAt\""
	UpdatedBy   *string                            "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
}

func (t *CreateUser_CreateUser_User) GetID() string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.ID
}
func (t *CreateUser_CreateUser_User) GetFirstName() string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.FirstName
}
func (t *CreateUser_CreateUser_User) GetLastName() string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.LastName
}
func (t *CreateUser_CreateUser_User) GetEmail() string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.Email
}
func (t *CreateUser_CreateUser_User) GetDisplayName() string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.DisplayName
}
func (t *CreateUser_CreateUser_User) GetSetting() *CreateUser_CreateUser_User_Setting {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return &t.Setting
}
func (t *CreateUser_CreateUser_User) GetCreatedAt() *time.Time {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return &t.CreatedAt
}
func (t *CreateUser_CreateUser_User) GetCreatedBy() *string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.CreatedBy
}
func (t *CreateUser_CreateUser_User) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return &t.UpdatedAt
}
func (t *CreateUser_CreateUser_User) GetUpdatedBy() *string {
	if t == nil {
		t = &CreateUser_CreateUser_User{}
	}
	return t.UpdatedBy
}

type CreateUser_CreateUser struct {
	User CreateUser_CreateUser_User "json:\"user\" graphql:\"user\""
}

func (t *CreateUser_CreateUser) GetUser() *CreateUser_CreateUser_User {
	if t == nil {
		t = &CreateUser_CreateUser{}
	}
	return &t.User
}

type UpdateUser_UpdateUser_User struct {
	ID          string    "json:\"id\" graphql:\"id\""
	FirstName   string    "json:\"firstName\" graphql:\"firstName\""
	LastName    string    "json:\"lastName\" graphql:\"lastName\""
	Email       string    "json:\"email\" graphql:\"email\""
	DisplayName string    "json:\"displayName\" graphql:\"displayName\""
	CreatedAt   time.Time "json:\"createdAt\" graphql:\"createdAt\""
	CreatedBy   *string   "json:\"createdBy,omitempty\" graphql:\"createdBy\""
	UpdatedAt   time.Time "json:\"updatedAt\" graphql:\"updatedAt\""
	UpdatedBy   *string   "json:\"updatedBy,omitempty\" graphql:\"updatedBy\""
}

func (t *UpdateUser_UpdateUser_User) GetID() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.ID
}
func (t *UpdateUser_UpdateUser_User) GetFirstName() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.FirstName
}
func (t *UpdateUser_UpdateUser_User) GetLastName() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.LastName
}
func (t *UpdateUser_UpdateUser_User) GetEmail() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.Email
}
func (t *UpdateUser_UpdateUser_User) GetDisplayName() string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.DisplayName
}
func (t *UpdateUser_UpdateUser_User) GetCreatedAt() *time.Time {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return &t.CreatedAt
}
func (t *UpdateUser_UpdateUser_User) GetCreatedBy() *string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.CreatedBy
}
func (t *UpdateUser_UpdateUser_User) GetUpdatedAt() *time.Time {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return &t.UpdatedAt
}
func (t *UpdateUser_UpdateUser_User) GetUpdatedBy() *string {
	if t == nil {
		t = &UpdateUser_UpdateUser_User{}
	}
	return t.UpdatedBy
}

type UpdateUser_UpdateUser struct {
	User UpdateUser_UpdateUser_User "json:\"user\" graphql:\"user\""
}

func (t *UpdateUser_UpdateUser) GetUser() *UpdateUser_UpdateUser_User {
	if t == nil {
		t = &UpdateUser_UpdateUser{}
	}
	return &t.User
}

type DeleteUser_DeleteUser struct {
	DeletedID string "json:\"deletedID\" graphql:\"deletedID\""
}

func (t *DeleteUser_DeleteUser) GetDeletedID() string {
	if t == nil {
		t = &DeleteUser_DeleteUser{}
	}
	return t.DeletedID
}

type GetOrganizationByID struct {
	Organization GetOrganizationByID_Organization "json:\"organization\" graphql:\"organization\""
}

func (t *GetOrganizationByID) GetOrganization() *GetOrganizationByID_Organization {
	if t == nil {
		t = &GetOrganizationByID{}
	}
	return &t.Organization
}

type GetAllOrganizations struct {
	Organizations GetAllOrganizations_Organizations "json:\"organizations\" graphql:\"organizations\""
}

func (t *GetAllOrganizations) GetOrganizations() *GetAllOrganizations_Organizations {
	if t == nil {
		t = &GetAllOrganizations{}
	}
	return &t.Organizations
}

type CreateOrganization struct {
	CreateOrganization CreateOrganization_CreateOrganization "json:\"createOrganization\" graphql:\"createOrganization\""
}

func (t *CreateOrganization) GetCreateOrganization() *CreateOrganization_CreateOrganization {
	if t == nil {
		t = &CreateOrganization{}
	}
	return &t.CreateOrganization
}

type UpdateOrganization struct {
	UpdateOrganization UpdateOrganization_UpdateOrganization "json:\"updateOrganization\" graphql:\"updateOrganization\""
}

func (t *UpdateOrganization) GetUpdateOrganization() *UpdateOrganization_UpdateOrganization {
	if t == nil {
		t = &UpdateOrganization{}
	}
	return &t.UpdateOrganization
}

type DeleteOrganization struct {
	DeleteOrganization DeleteOrganization_DeleteOrganization "json:\"deleteOrganization\" graphql:\"deleteOrganization\""
}

func (t *DeleteOrganization) GetDeleteOrganization() *DeleteOrganization_DeleteOrganization {
	if t == nil {
		t = &DeleteOrganization{}
	}
	return &t.DeleteOrganization
}

type GetUserByID struct {
	User GetUserByID_User "json:\"user\" graphql:\"user\""
}

func (t *GetUserByID) GetUser() *GetUserByID_User {
	if t == nil {
		t = &GetUserByID{}
	}
	return &t.User
}

type GetUserByIDWithOrgs struct {
	User GetUserByIDWithOrgs_User "json:\"user\" graphql:\"user\""
}

func (t *GetUserByIDWithOrgs) GetUser() *GetUserByIDWithOrgs_User {
	if t == nil {
		t = &GetUserByIDWithOrgs{}
	}
	return &t.User
}

type GetAllUsers struct {
	Users GetAllUsers_Users "json:\"users\" graphql:\"users\""
}

func (t *GetAllUsers) GetUsers() *GetAllUsers_Users {
	if t == nil {
		t = &GetAllUsers{}
	}
	return &t.Users
}

type CreateUser struct {
	CreateUser CreateUser_CreateUser "json:\"createUser\" graphql:\"createUser\""
}

func (t *CreateUser) GetCreateUser() *CreateUser_CreateUser {
	if t == nil {
		t = &CreateUser{}
	}
	return &t.CreateUser
}

type UpdateUser struct {
	UpdateUser UpdateUser_UpdateUser "json:\"updateUser\" graphql:\"updateUser\""
}

func (t *UpdateUser) GetUpdateUser() *UpdateUser_UpdateUser {
	if t == nil {
		t = &UpdateUser{}
	}
	return &t.UpdateUser
}

type DeleteUser struct {
	DeleteUser DeleteUser_DeleteUser "json:\"deleteUser\" graphql:\"deleteUser\""
}

func (t *DeleteUser) GetDeleteUser() *DeleteUser_DeleteUser {
	if t == nil {
		t = &DeleteUser{}
	}
	return &t.DeleteUser
}

const GetOrganizationByIDDocument = `query GetOrganizationByID ($organizationId: ID!) {
	organization(id: $organizationId) {
		id
		name
		displayName
		description
		createdAt
		createdBy
		updatedAt
		updatedBy
	}
}
`

func (c *Client) GetOrganizationByID(ctx context.Context, organizationID string, interceptors ...clientv2.RequestInterceptor) (*GetOrganizationByID, error) {
	vars := map[string]interface{}{
		"organizationId": organizationID,
	}

	var res GetOrganizationByID
	if err := c.Client.Post(ctx, "GetOrganizationByID", GetOrganizationByIDDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetAllOrganizationsDocument = `query GetAllOrganizations {
	organizations {
		edges {
			node {
				id
				name
				displayName
				description
			}
		}
	}
}
`

func (c *Client) GetAllOrganizations(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetAllOrganizations, error) {
	vars := map[string]interface{}{}

	var res GetAllOrganizations
	if err := c.Client.Post(ctx, "GetAllOrganizations", GetAllOrganizationsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateOrganizationDocument = `mutation CreateOrganization ($input: CreateOrganizationInput!) {
	createOrganization(input: $input) {
		organization {
			id
			name
			displayName
			description
			createdAt
			createdBy
			updatedAt
			updatedBy
		}
	}
}
`

func (c *Client) CreateOrganization(ctx context.Context, input CreateOrganizationInput, interceptors ...clientv2.RequestInterceptor) (*CreateOrganization, error) {
	vars := map[string]interface{}{
		"input": input,
	}

	var res CreateOrganization
	if err := c.Client.Post(ctx, "CreateOrganization", CreateOrganizationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdateOrganizationDocument = `mutation UpdateOrganization ($updateOrganizationId: ID!, $input: UpdateOrganizationInput!) {
	updateOrganization(id: $updateOrganizationId, input: $input) {
		organization {
			id
			name
			displayName
			description
		}
	}
}
`

func (c *Client) UpdateOrganization(ctx context.Context, updateOrganizationID string, input UpdateOrganizationInput, interceptors ...clientv2.RequestInterceptor) (*UpdateOrganization, error) {
	vars := map[string]interface{}{
		"updateOrganizationId": updateOrganizationID,
		"input":                input,
	}

	var res UpdateOrganization
	if err := c.Client.Post(ctx, "UpdateOrganization", UpdateOrganizationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeleteOrganizationDocument = `mutation DeleteOrganization ($deleteOrganizationId: ID!) {
	deleteOrganization(id: $deleteOrganizationId) {
		deletedID
	}
}
`

func (c *Client) DeleteOrganization(ctx context.Context, deleteOrganizationID string, interceptors ...clientv2.RequestInterceptor) (*DeleteOrganization, error) {
	vars := map[string]interface{}{
		"deleteOrganizationId": deleteOrganizationID,
	}

	var res DeleteOrganization
	if err := c.Client.Post(ctx, "DeleteOrganization", DeleteOrganizationDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserByIDDocument = `query GetUserByID ($userId: ID!) {
	user(id: $userId) {
		id
		firstName
		lastName
		email
		displayName
		setting {
			status
			locked
			emailConfirmed
		}
	}
}
`

func (c *Client) GetUserByID(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUserByID, error) {
	vars := map[string]interface{}{
		"userId": userID,
	}

	var res GetUserByID
	if err := c.Client.Post(ctx, "GetUserByID", GetUserByIDDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetUserByIDWithOrgsDocument = `query GetUserByIDWithOrgs ($userId: ID!) {
	user(id: $userId) {
		id
		firstName
		lastName
		email
		displayName
		setting {
			status
			locked
			emailConfirmed
		}
		organizations {
			id
			name
			displayName
		}
	}
}
`

func (c *Client) GetUserByIDWithOrgs(ctx context.Context, userID string, interceptors ...clientv2.RequestInterceptor) (*GetUserByIDWithOrgs, error) {
	vars := map[string]interface{}{
		"userId": userID,
	}

	var res GetUserByIDWithOrgs
	if err := c.Client.Post(ctx, "GetUserByIDWithOrgs", GetUserByIDWithOrgsDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const GetAllUsersDocument = `query GetAllUsers {
	users {
		edges {
			node {
				id
				firstName
				lastName
				email
				displayName
				setting {
					status
					locked
					emailConfirmed
				}
			}
		}
	}
}
`

func (c *Client) GetAllUsers(ctx context.Context, interceptors ...clientv2.RequestInterceptor) (*GetAllUsers, error) {
	vars := map[string]interface{}{}

	var res GetAllUsers
	if err := c.Client.Post(ctx, "GetAllUsers", GetAllUsersDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const CreateUserDocument = `mutation CreateUser ($input: CreateUserInput!) {
	createUser(input: $input) {
		user {
			id
			firstName
			lastName
			email
			displayName
			setting {
				status
				locked
				emailConfirmed
			}
			createdAt
			createdBy
			updatedAt
			updatedBy
		}
	}
}
`

func (c *Client) CreateUser(ctx context.Context, input CreateUserInput, interceptors ...clientv2.RequestInterceptor) (*CreateUser, error) {
	vars := map[string]interface{}{
		"input": input,
	}

	var res CreateUser
	if err := c.Client.Post(ctx, "CreateUser", CreateUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const UpdateUserDocument = `mutation UpdateUser ($updateUserId: ID!, $input: UpdateUserInput!) {
	updateUser(id: $updateUserId, input: $input) {
		user {
			id
			firstName
			lastName
			email
			displayName
			createdAt
			createdBy
			updatedAt
			updatedBy
		}
	}
}
`

func (c *Client) UpdateUser(ctx context.Context, updateUserID string, input UpdateUserInput, interceptors ...clientv2.RequestInterceptor) (*UpdateUser, error) {
	vars := map[string]interface{}{
		"updateUserId": updateUserID,
		"input":        input,
	}

	var res UpdateUser
	if err := c.Client.Post(ctx, "UpdateUser", UpdateUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

const DeleteUserDocument = `mutation DeleteUser ($deleteUserId: ID!) {
	deleteUser(id: $deleteUserId) {
		deletedID
	}
}
`

func (c *Client) DeleteUser(ctx context.Context, deleteUserID string, interceptors ...clientv2.RequestInterceptor) (*DeleteUser, error) {
	vars := map[string]interface{}{
		"deleteUserId": deleteUserID,
	}

	var res DeleteUser
	if err := c.Client.Post(ctx, "DeleteUser", DeleteUserDocument, &res, vars, interceptors...); err != nil {
		if c.Client.ParseDataWhenErrors {
			return &res, err
		}

		return nil, err
	}

	return &res, nil
}

var DocumentOperationNames = map[string]string{
	GetOrganizationByIDDocument: "GetOrganizationByID",
	GetAllOrganizationsDocument: "GetAllOrganizations",
	CreateOrganizationDocument:  "CreateOrganization",
	UpdateOrganizationDocument:  "UpdateOrganization",
	DeleteOrganizationDocument:  "DeleteOrganization",
	GetUserByIDDocument:         "GetUserByID",
	GetUserByIDWithOrgsDocument: "GetUserByIDWithOrgs",
	GetAllUsersDocument:         "GetAllUsers",
	CreateUserDocument:          "CreateUser",
	UpdateUserDocument:          "UpdateUser",
	DeleteUserDocument:          "DeleteUser",
}
