// Code generated by github.com/Yamashou/gqlgenc, DO NOT EDIT.

package testclient

import (
	"net/http"

	"github.com/Yamashou/gqlgenc/client"
	"github.com/datumforge/datum/internal/ent/generated"
)

type TestClient interface {
}

type Client struct {
	Client *client.Client
}

func NewClient(cli *http.Client, baseURL string, options ...client.HTTPRequestOption) TestClient {
	return &Client{Client: client.NewClient(cli, baseURL, options...)}
}

type Query struct {
	Node          generated.Noder   "json:\"node\" graphql:\"node\""
	Nodes         []generated.Noder "json:\"nodes\" graphql:\"nodes\""
	Integrations  []*Integration    "json:\"integrations\" graphql:\"integrations\""
	Memberships   []*Membership     "json:\"memberships\" graphql:\"memberships\""
	Organizations []*Organization   "json:\"organizations\" graphql:\"organizations\""
	Users         []*User           "json:\"users\" graphql:\"users\""
	Service       Service           "json:\"_service\" graphql:\"_service\""
}
