package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateOauthProvider is the resolver for the createOauthProvider field.
func (r *mutationResolver) CreateOauthProvider(ctx context.Context, input generated.CreateOauthProviderInput) (*OauthProviderCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateOauthProvider - createOauthProvider"))
}

// UpdateOauthProvider is the resolver for the updateOauthProvider field.
func (r *mutationResolver) UpdateOauthProvider(ctx context.Context, id string, input generated.UpdateOauthProviderInput) (*OauthProviderUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateOauthProvider - updateOauthProvider"))
}

// DeleteOauthProvider is the resolver for the deleteOauthProvider field.
func (r *mutationResolver) DeleteOauthProvider(ctx context.Context, id string) (*OauthProviderDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteOauthProvider - deleteOauthProvider"))
}

// OauthProvider is the resolver for the OauthProvider field.
func (r *queryResolver) OauthProvider(ctx context.Context, id string) (*generated.OauthProvider, error) {
	panic(fmt.Errorf("not implemented: OauthProvider - OauthProvider"))
}
