package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateOhAuthTooToken is the resolver for the createOhAuthTooToken field.
func (r *mutationResolver) CreateOhAuthTooToken(ctx context.Context, input generated.CreateOhAuthTooTokenInput) (*OhAuthTooTokenCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateOhAuthTooToken - createOhAuthTooToken"))
}

// UpdateOhAuthTooToken is the resolver for the updateOhAuthTooToken field.
func (r *mutationResolver) UpdateOhAuthTooToken(ctx context.Context, id string, input generated.UpdateOhAuthTooTokenInput) (*OhAuthTooTokenUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateOhAuthTooToken - updateOhAuthTooToken"))
}

// DeleteOhAuthTooToken is the resolver for the deleteOhAuthTooToken field.
func (r *mutationResolver) DeleteOhAuthTooToken(ctx context.Context, id string) (*OhAuthTooTokenDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteOhAuthTooToken - deleteOhAuthTooToken"))
}

// OhAuthTooToken is the resolver for the ohAuthTooToken field.
func (r *queryResolver) OhAuthTooToken(ctx context.Context, id string) (*generated.OhAuthTooToken, error) {
	panic(fmt.Errorf("not implemented: OhAuthTooToken - ohAuthTooToken"))
}
