env:
  APP_NAME: ${BUILDKITE_PIPELINE_SLUG}
  IMAGE_REPO: ghcr.io/datumforge/${APP_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT:0:8}

steps:
- label: ":golangci-lint: lint :lint-roller:"
  key: "lint"
  plugins:
    - docker#v5.9.0:
        image: "registry.hub.docker.com/golangci/golangci-lint:v1.55.2"
        command: ["golangci-lint", "run", "-v", "--timeout", "10m"]
        environment: 
          - "GOTOOLCHAIN=auto"

- label: ":test_tube: go test"
  key: "test"
  plugins:
    - docker#v5.9.0:
        image: golang:1.21.4
        command: ["go", "test", "./..."]

- label: ":auth0: fga model test"
  key: "fga_test"
  plugins:
    - docker#v5.9.0:
        image: openfga/cli
        command: ["model", "test", "--tests", "fga/tests/tests.yaml"]

- label: ":golang: build"
  key: "gobuild"
  artifact_paths: "bin/${APP_NAME}"
  plugins:
    - docker#v5.9.0:
        image: "golang:1.21.4"
        environment:
          - CGO_ENABLED=0
          - GOOS=linux
        command: ["go", "build", "-buildvcs=false", "-mod=mod", "-a", "-o", "bin/$APP_NAME"]