package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// ID is the resolver for the id field.
func (r *integrationResolver) ID(ctx context.Context, obj *generated.Integration) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *membershipResolver) ID(ctx context.Context, obj *generated.Membership) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *organizationResolver) ID(ctx context.Context, obj *generated.Organization) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id string) (generated.Noder, error) {
	panic(fmt.Errorf("not implemented: Node - node"))
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []string) ([]generated.Noder, error) {
	panic(fmt.Errorf("not implemented: Nodes - nodes"))
}

// Integrations is the resolver for the integrations field.
func (r *queryResolver) Integrations(ctx context.Context) ([]*generated.Integration, error) {
	panic(fmt.Errorf("not implemented: Integrations - integrations"))
}

// Memberships is the resolver for the memberships field.
func (r *queryResolver) Memberships(ctx context.Context) ([]*generated.Membership, error) {
	panic(fmt.Errorf("not implemented: Memberships - memberships"))
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*generated.Organization, error) {
	panic(fmt.Errorf("not implemented: Organizations - organizations"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*generated.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// ID is the resolver for the id field.
func (r *sessionResolver) ID(ctx context.Context, obj *generated.Session) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *generated.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// OrganizationID is the resolver for the organizationID field.
func (r *createIntegrationInputResolver) OrganizationID(ctx context.Context, obj *generated.CreateIntegrationInput, data string) error {
	panic(fmt.Errorf("not implemented: OrganizationID - organizationID"))
}

// OrganizationID is the resolver for the organizationID field.
func (r *createMembershipInputResolver) OrganizationID(ctx context.Context, obj *generated.CreateMembershipInput, data string) error {
	panic(fmt.Errorf("not implemented: OrganizationID - organizationID"))
}

// UserID is the resolver for the userID field.
func (r *createMembershipInputResolver) UserID(ctx context.Context, obj *generated.CreateMembershipInput, data string) error {
	panic(fmt.Errorf("not implemented: UserID - userID"))
}

// MembershipIDs is the resolver for the membershipIDs field.
func (r *createOrganizationInputResolver) MembershipIDs(ctx context.Context, obj *generated.CreateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: MembershipIDs - membershipIDs"))
}

// IntegrationIDs is the resolver for the integrationIDs field.
func (r *createOrganizationInputResolver) IntegrationIDs(ctx context.Context, obj *generated.CreateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: IntegrationIDs - integrationIDs"))
}

// MembershipIDs is the resolver for the membershipIDs field.
func (r *createUserInputResolver) MembershipIDs(ctx context.Context, obj *generated.CreateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: MembershipIDs - membershipIDs"))
}

// SessionIDs is the resolver for the sessionIDs field.
func (r *createUserInputResolver) SessionIDs(ctx context.Context, obj *generated.CreateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: SessionIDs - sessionIDs"))
}

// ID is the resolver for the id field.
func (r *integrationWhereInputResolver) ID(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// IDNeq is the resolver for the idNEQ field.
func (r *integrationWhereInputResolver) IDNeq(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDNeq - idNEQ"))
}

// IDIn is the resolver for the idIn field.
func (r *integrationWhereInputResolver) IDIn(ctx context.Context, obj *generated.IntegrationWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDIn - idIn"))
}

// IDNotIn is the resolver for the idNotIn field.
func (r *integrationWhereInputResolver) IDNotIn(ctx context.Context, obj *generated.IntegrationWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDNotIn - idNotIn"))
}

// IDGt is the resolver for the idGT field.
func (r *integrationWhereInputResolver) IDGt(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGt - idGT"))
}

// IDGte is the resolver for the idGTE field.
func (r *integrationWhereInputResolver) IDGte(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGte - idGTE"))
}

// IDLt is the resolver for the idLT field.
func (r *integrationWhereInputResolver) IDLt(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLt - idLT"))
}

// IDLte is the resolver for the idLTE field.
func (r *integrationWhereInputResolver) IDLte(ctx context.Context, obj *generated.IntegrationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLte - idLTE"))
}

// ID is the resolver for the id field.
func (r *membershipWhereInputResolver) ID(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// IDNeq is the resolver for the idNEQ field.
func (r *membershipWhereInputResolver) IDNeq(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDNeq - idNEQ"))
}

// IDIn is the resolver for the idIn field.
func (r *membershipWhereInputResolver) IDIn(ctx context.Context, obj *generated.MembershipWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDIn - idIn"))
}

// IDNotIn is the resolver for the idNotIn field.
func (r *membershipWhereInputResolver) IDNotIn(ctx context.Context, obj *generated.MembershipWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDNotIn - idNotIn"))
}

// IDGt is the resolver for the idGT field.
func (r *membershipWhereInputResolver) IDGt(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGt - idGT"))
}

// IDGte is the resolver for the idGTE field.
func (r *membershipWhereInputResolver) IDGte(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGte - idGTE"))
}

// IDLt is the resolver for the idLT field.
func (r *membershipWhereInputResolver) IDLt(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLt - idLT"))
}

// IDLte is the resolver for the idLTE field.
func (r *membershipWhereInputResolver) IDLte(ctx context.Context, obj *generated.MembershipWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLte - idLTE"))
}

// ID is the resolver for the id field.
func (r *organizationWhereInputResolver) ID(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// IDNeq is the resolver for the idNEQ field.
func (r *organizationWhereInputResolver) IDNeq(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDNeq - idNEQ"))
}

// IDIn is the resolver for the idIn field.
func (r *organizationWhereInputResolver) IDIn(ctx context.Context, obj *generated.OrganizationWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDIn - idIn"))
}

// IDNotIn is the resolver for the idNotIn field.
func (r *organizationWhereInputResolver) IDNotIn(ctx context.Context, obj *generated.OrganizationWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDNotIn - idNotIn"))
}

// IDGt is the resolver for the idGT field.
func (r *organizationWhereInputResolver) IDGt(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGt - idGT"))
}

// IDGte is the resolver for the idGTE field.
func (r *organizationWhereInputResolver) IDGte(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGte - idGTE"))
}

// IDLt is the resolver for the idLT field.
func (r *organizationWhereInputResolver) IDLt(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLt - idLT"))
}

// IDLte is the resolver for the idLTE field.
func (r *organizationWhereInputResolver) IDLte(ctx context.Context, obj *generated.OrganizationWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLte - idLTE"))
}

// ID is the resolver for the id field.
func (r *sessionWhereInputResolver) ID(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// IDNeq is the resolver for the idNEQ field.
func (r *sessionWhereInputResolver) IDNeq(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDNeq - idNEQ"))
}

// IDIn is the resolver for the idIn field.
func (r *sessionWhereInputResolver) IDIn(ctx context.Context, obj *generated.SessionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDIn - idIn"))
}

// IDNotIn is the resolver for the idNotIn field.
func (r *sessionWhereInputResolver) IDNotIn(ctx context.Context, obj *generated.SessionWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDNotIn - idNotIn"))
}

// IDGt is the resolver for the idGT field.
func (r *sessionWhereInputResolver) IDGt(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGt - idGT"))
}

// IDGte is the resolver for the idGTE field.
func (r *sessionWhereInputResolver) IDGte(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGte - idGTE"))
}

// IDLt is the resolver for the idLT field.
func (r *sessionWhereInputResolver) IDLt(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLt - idLT"))
}

// IDLte is the resolver for the idLTE field.
func (r *sessionWhereInputResolver) IDLte(ctx context.Context, obj *generated.SessionWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLte - idLTE"))
}

// OrganizationID is the resolver for the organizationID field.
func (r *updateIntegrationInputResolver) OrganizationID(ctx context.Context, obj *generated.UpdateIntegrationInput, data *string) error {
	panic(fmt.Errorf("not implemented: OrganizationID - organizationID"))
}

// OrganizationID is the resolver for the organizationID field.
func (r *updateMembershipInputResolver) OrganizationID(ctx context.Context, obj *generated.UpdateMembershipInput, data *string) error {
	panic(fmt.Errorf("not implemented: OrganizationID - organizationID"))
}

// UserID is the resolver for the userID field.
func (r *updateMembershipInputResolver) UserID(ctx context.Context, obj *generated.UpdateMembershipInput, data *string) error {
	panic(fmt.Errorf("not implemented: UserID - userID"))
}

// AddMembershipIDs is the resolver for the addMembershipIDs field.
func (r *updateOrganizationInputResolver) AddMembershipIDs(ctx context.Context, obj *generated.UpdateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: AddMembershipIDs - addMembershipIDs"))
}

// RemoveMembershipIDs is the resolver for the removeMembershipIDs field.
func (r *updateOrganizationInputResolver) RemoveMembershipIDs(ctx context.Context, obj *generated.UpdateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: RemoveMembershipIDs - removeMembershipIDs"))
}

// AddIntegrationIDs is the resolver for the addIntegrationIDs field.
func (r *updateOrganizationInputResolver) AddIntegrationIDs(ctx context.Context, obj *generated.UpdateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: AddIntegrationIDs - addIntegrationIDs"))
}

// RemoveIntegrationIDs is the resolver for the removeIntegrationIDs field.
func (r *updateOrganizationInputResolver) RemoveIntegrationIDs(ctx context.Context, obj *generated.UpdateOrganizationInput, data []string) error {
	panic(fmt.Errorf("not implemented: RemoveIntegrationIDs - removeIntegrationIDs"))
}

// AddMembershipIDs is the resolver for the addMembershipIDs field.
func (r *updateUserInputResolver) AddMembershipIDs(ctx context.Context, obj *generated.UpdateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: AddMembershipIDs - addMembershipIDs"))
}

// RemoveMembershipIDs is the resolver for the removeMembershipIDs field.
func (r *updateUserInputResolver) RemoveMembershipIDs(ctx context.Context, obj *generated.UpdateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: RemoveMembershipIDs - removeMembershipIDs"))
}

// AddSessionIDs is the resolver for the addSessionIDs field.
func (r *updateUserInputResolver) AddSessionIDs(ctx context.Context, obj *generated.UpdateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: AddSessionIDs - addSessionIDs"))
}

// RemoveSessionIDs is the resolver for the removeSessionIDs field.
func (r *updateUserInputResolver) RemoveSessionIDs(ctx context.Context, obj *generated.UpdateUserInput, data []string) error {
	panic(fmt.Errorf("not implemented: RemoveSessionIDs - removeSessionIDs"))
}

// ID is the resolver for the id field.
func (r *userWhereInputResolver) ID(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// IDNeq is the resolver for the idNEQ field.
func (r *userWhereInputResolver) IDNeq(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDNeq - idNEQ"))
}

// IDIn is the resolver for the idIn field.
func (r *userWhereInputResolver) IDIn(ctx context.Context, obj *generated.UserWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDIn - idIn"))
}

// IDNotIn is the resolver for the idNotIn field.
func (r *userWhereInputResolver) IDNotIn(ctx context.Context, obj *generated.UserWhereInput, data []string) error {
	panic(fmt.Errorf("not implemented: IDNotIn - idNotIn"))
}

// IDGt is the resolver for the idGT field.
func (r *userWhereInputResolver) IDGt(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGt - idGT"))
}

// IDGte is the resolver for the idGTE field.
func (r *userWhereInputResolver) IDGte(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDGte - idGTE"))
}

// IDLt is the resolver for the idLT field.
func (r *userWhereInputResolver) IDLt(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLt - idLT"))
}

// IDLte is the resolver for the idLTE field.
func (r *userWhereInputResolver) IDLte(ctx context.Context, obj *generated.UserWhereInput, data *string) error {
	panic(fmt.Errorf("not implemented: IDLte - idLTE"))
}

// Integration returns IntegrationResolver implementation.
func (r *Resolver) Integration() IntegrationResolver { return &integrationResolver{r} }

// Membership returns MembershipResolver implementation.
func (r *Resolver) Membership() MembershipResolver { return &membershipResolver{r} }

// Organization returns OrganizationResolver implementation.
func (r *Resolver) Organization() OrganizationResolver { return &organizationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Session returns SessionResolver implementation.
func (r *Resolver) Session() SessionResolver { return &sessionResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

// CreateIntegrationInput returns CreateIntegrationInputResolver implementation.
func (r *Resolver) CreateIntegrationInput() CreateIntegrationInputResolver {
	return &createIntegrationInputResolver{r}
}

// CreateMembershipInput returns CreateMembershipInputResolver implementation.
func (r *Resolver) CreateMembershipInput() CreateMembershipInputResolver {
	return &createMembershipInputResolver{r}
}

// CreateOrganizationInput returns CreateOrganizationInputResolver implementation.
func (r *Resolver) CreateOrganizationInput() CreateOrganizationInputResolver {
	return &createOrganizationInputResolver{r}
}

// CreateUserInput returns CreateUserInputResolver implementation.
func (r *Resolver) CreateUserInput() CreateUserInputResolver { return &createUserInputResolver{r} }

// IntegrationWhereInput returns IntegrationWhereInputResolver implementation.
func (r *Resolver) IntegrationWhereInput() IntegrationWhereInputResolver {
	return &integrationWhereInputResolver{r}
}

// MembershipWhereInput returns MembershipWhereInputResolver implementation.
func (r *Resolver) MembershipWhereInput() MembershipWhereInputResolver {
	return &membershipWhereInputResolver{r}
}

// OrganizationWhereInput returns OrganizationWhereInputResolver implementation.
func (r *Resolver) OrganizationWhereInput() OrganizationWhereInputResolver {
	return &organizationWhereInputResolver{r}
}

// SessionWhereInput returns SessionWhereInputResolver implementation.
func (r *Resolver) SessionWhereInput() SessionWhereInputResolver {
	return &sessionWhereInputResolver{r}
}

// UpdateIntegrationInput returns UpdateIntegrationInputResolver implementation.
func (r *Resolver) UpdateIntegrationInput() UpdateIntegrationInputResolver {
	return &updateIntegrationInputResolver{r}
}

// UpdateMembershipInput returns UpdateMembershipInputResolver implementation.
func (r *Resolver) UpdateMembershipInput() UpdateMembershipInputResolver {
	return &updateMembershipInputResolver{r}
}

// UpdateOrganizationInput returns UpdateOrganizationInputResolver implementation.
func (r *Resolver) UpdateOrganizationInput() UpdateOrganizationInputResolver {
	return &updateOrganizationInputResolver{r}
}

// UpdateUserInput returns UpdateUserInputResolver implementation.
func (r *Resolver) UpdateUserInput() UpdateUserInputResolver { return &updateUserInputResolver{r} }

// UserWhereInput returns UserWhereInputResolver implementation.
func (r *Resolver) UserWhereInput() UserWhereInputResolver { return &userWhereInputResolver{r} }

type integrationResolver struct{ *Resolver }
type membershipResolver struct{ *Resolver }
type organizationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sessionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
type createIntegrationInputResolver struct{ *Resolver }
type createMembershipInputResolver struct{ *Resolver }
type createOrganizationInputResolver struct{ *Resolver }
type createUserInputResolver struct{ *Resolver }
type integrationWhereInputResolver struct{ *Resolver }
type membershipWhereInputResolver struct{ *Resolver }
type organizationWhereInputResolver struct{ *Resolver }
type sessionWhereInputResolver struct{ *Resolver }
type updateIntegrationInputResolver struct{ *Resolver }
type updateMembershipInputResolver struct{ *Resolver }
type updateOrganizationInputResolver struct{ *Resolver }
type updateUserInputResolver struct{ *Resolver }
type userWhereInputResolver struct{ *Resolver }
