// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"github.com/datumforge/datum/internal/ent/generated"
)

// Return response for createEntitlement mutation
type EntitlementCreatePayload struct {
	// Created entitlement
	Entitlement *generated.Entitlement `json:"entitlement"`
}

// Return response for deleteEntitlement mutation
type EntitlementDeletePayload struct {
	// Deleted entitlement ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateEntitlement mutation
type EntitlementUpdatePayload struct {
	// Updated entitlement
	Entitlement *generated.Entitlement `json:"entitlement"`
}

// Return response for createGroup mutation
type GroupCreatePayload struct {
	// Created group
	Group *generated.Group `json:"group"`
}

// Return response for deleteGroup mutation
type GroupDeletePayload struct {
	// Deleted group ID
	DeletedID string `json:"deletedID"`
}

// Return response for createGroupSetting mutation
type GroupSettingCreatePayload struct {
	// Created groupSetting
	GroupSetting *generated.GroupSetting `json:"groupSetting"`
}

// Return response for deleteGroupSetting mutation
type GroupSettingDeletePayload struct {
	// Deleted groupSetting ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateGroupSetting mutation
type GroupSettingUpdatePayload struct {
	// Updated groupSetting
	GroupSetting *generated.GroupSetting `json:"groupSetting"`
}

// Return response for updateGroup mutation
type GroupUpdatePayload struct {
	// Updated group
	Group *generated.Group `json:"group"`
}

// Return response for createIntegration mutation
type IntegrationCreatePayload struct {
	// Created integration
	Integration *generated.Integration `json:"integration"`
}

// Return response for deleteIntegration mutation
type IntegrationDeletePayload struct {
	// Deleted integration ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateIntegration mutation
type IntegrationUpdatePayload struct {
	// Updated integration
	Integration *generated.Integration `json:"integration"`
}

// Return response for createOauthprovider mutation
type OauthProviderCreatePayload struct {
	// Created oauthProvider
	OauthProvider *generated.OauthProvider `json:"OauthProvider"`
}

// Return response for deleteOauthprovider mutation
type OauthProviderDeletePayload struct {
	// Deleted oauthProvider ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateOauthprovider mutation
type OauthProviderUpdatePayload struct {
	// Updated oauthProvider
	OauthProvider *generated.OauthProvider `json:"OauthProvider"`
}

// Return response for createOrganization mutation
type OrganizationCreatePayload struct {
	// Created organization
	Organization *generated.Organization `json:"organization"`
}

// Return response for deleteOrganization mutation
type OrganizationDeletePayload struct {
	// Deleted organization ID
	DeletedID string `json:"deletedID"`
}

// Return response for createOrganizationSetting mutation
type OrganizationSettingCreatePayload struct {
	// Created organizationSetting
	OrganizationSetting *generated.OrganizationSetting `json:"organizationSetting"`
}

// Return response for deleteOrganizationSetting mutation
type OrganizationSettingDeletePayload struct {
	// Deleted organizationSetting ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateOrganizationSetting mutation
type OrganizationSettingUpdatePayload struct {
	// Updated organizationSetting
	OrganizationSetting *generated.OrganizationSetting `json:"organizationSetting"`
}

// Return response for updateOrganization mutation
type OrganizationUpdatePayload struct {
	// Updated organization
	Organization *generated.Organization `json:"organization"`
}

// Return response for createPersonalAccessToken mutation
type PersonalAccessTokenCreatePayload struct {
	// Created personalAccessToken
	PersonalAccessToken *generated.PersonalAccessToken `json:"PersonalAccessToken"`
}

// Return response for deletePersonalAccessToken mutation
type PersonalAccessTokenDeletePayload struct {
	// Deleted personalAccessToken ID
	DeletedID string `json:"deletedID"`
}

// Return response for updatePersonalAccessToken mutation
type PersonalAccessTokenUpdatePayload struct {
	// Updated personalAccessToken
	PersonalAccessToken *generated.PersonalAccessToken `json:"PersonalAccessToken"`
}

// Return response for createRefreshToken mutation
type RefreshTokenCreatePayload struct {
	// Created refreshToken
	RefreshToken *generated.RefreshToken `json:"refreshToken"`
}

// Return response for deleteRefreshToken mutation
type RefreshTokenDeletePayload struct {
	// Deleted refreshToken ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateRefreshToken mutation
type RefreshTokenUpdatePayload struct {
	// Updated refreshToken
	RefreshToken *generated.RefreshToken `json:"refreshToken"`
}

// Return response for createSession mutation
type SessionCreatePayload struct {
	// Created session
	Session *generated.Session `json:"session"`
}

// Return response for deleteSession mutation
type SessionDeletePayload struct {
	// Deleted session ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateSession mutation
type SessionUpdatePayload struct {
	// Updated session
	Session *generated.Session `json:"session"`
}

// Return response for createUser mutation
type UserCreatePayload struct {
	// Created user
	User *generated.User `json:"user"`
}

// Return response for deleteUser mutation
type UserDeletePayload struct {
	// Deleted user ID
	DeletedID string `json:"deletedID"`
}

// Return response for createUserSetting mutation
type UserSettingCreatePayload struct {
	// Created userSetting
	UserSetting *generated.UserSetting `json:"UserSetting"`
}

// Return response for deleteUserSetting mutation
type UserSettingDeletePayload struct {
	// Deleted userSetting ID
	DeletedID string `json:"deletedID"`
}

// Return response for updateUserSetting mutation
type UserSettingUpdatePayload struct {
	// Updated userSetting
	UserSetting *generated.UserSetting `json:"UserSetting"`
}

// Return response for updateUser mutation
type UserUpdatePayload struct {
	// Updated user
	User *generated.User `json:"user"`
}
