package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateRefreshToken is the resolver for the createRefreshToken field.
func (r *mutationResolver) CreateRefreshToken(ctx context.Context, input generated.CreateRefreshTokenInput) (*RefreshTokenCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateRefreshToken - createRefreshToken"))
}

// UpdateRefreshToken is the resolver for the updateRefreshToken field.
func (r *mutationResolver) UpdateRefreshToken(ctx context.Context, id string, input generated.UpdateRefreshTokenInput) (*RefreshTokenUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateRefreshToken - updateRefreshToken"))
}

// DeleteRefreshToken is the resolver for the deleteRefreshToken field.
func (r *mutationResolver) DeleteRefreshToken(ctx context.Context, id string) (*RefreshTokenDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteRefreshToken - deleteRefreshToken"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *queryResolver) RefreshToken(ctx context.Context, id string) (*generated.RefreshToken, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}
