package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.39

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
	"github.com/google/uuid"
)

// CreateSession is the resolver for the createSession field.
func (r *mutationResolver) CreateSession(ctx context.Context, input generated.CreateSessionInput) (*SessionCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateSession - createSession"))
}

// UpdateSession is the resolver for the updateSession field.
func (r *mutationResolver) UpdateSession(ctx context.Context, id uuid.UUID, input generated.UpdateSessionInput) (*SessionUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateSession - updateSession"))
}

// DeleteSession is the resolver for the deleteSession field.
func (r *mutationResolver) DeleteSession(ctx context.Context, id uuid.UUID) (*SessionDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteSession - deleteSession"))
}

// Session is the resolver for the session field.
func (r *queryResolver) Session(ctx context.Context, id uuid.UUID) (*generated.Session, error) {
	panic(fmt.Errorf("not implemented: Session - session"))
}
