package api

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"

	"github.com/datumforge/datum/internal/ent/generated"
)

// CreateUserSettingsInput is the resolver for the CreateUserSettingsInput field.
func (r *mutationResolver) CreateUserSettingsInput(ctx context.Context, input generated.CreateUserSettingsInput) (*UserSettingsCreatePayload, error) {
	panic(fmt.Errorf("not implemented: CreateUserSettingsInput - CreateUserSettingsInput"))
}

// UpdateUserSettingsInput is the resolver for the UpdateUserSettingsInput field.
func (r *mutationResolver) UpdateUserSettingsInput(ctx context.Context, id string, input generated.UpdateUserSettingsInput) (*UserSettingsUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: UpdateUserSettingsInput - UpdateUserSettingsInput"))
}

// DeleteUserSettings is the resolver for the DeleteUserSettings field.
func (r *mutationResolver) DeleteUserSettings(ctx context.Context, id string) (*UserSettingsDeletePayload, error) {
	panic(fmt.Errorf("not implemented: DeleteUserSettings - DeleteUserSettings"))
}

// UserSettings is the resolver for the UserSettings field.
func (r *queryResolver) UserSettings(ctx context.Context, id string) (*generated.UserSettings, error) {
	panic(fmt.Errorf("not implemented: UserSettings - UserSettings"))
}
